- name: nodejs image install and run
  hosts: _ansible_nodejs
  become: true
  tasks:

    - name: copy files to the nodejs node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible/ansible-project/nodejs/
        dest: /home/ec2-user/nodejs

  # Remove the container if it exists
    - name: remove cw_nodejs container
      community.docker.docker_container:
        name: cw_nodejs
        state: absent
        force_kill: true

  # Remove the image if it exists
    - name: remove clarusway/nodejs image
      community.docker.docker_image:
        name: clarusway/nodejs
        state: absent

    - name: build container image
      community.docker.docker_image:
        name: clarusway/nodejs
        build:
          path: /home/ec2-user/nodejs
        source: build
        state: present
      register: image_info

    - name: print the image info
      ansible.builtin.debug:
        var: image_info

    - name: Launch nodejs docker container
      community.docker.docker_container:
        name: cw_nodejs
        image: clarusway/nodejs
        state: started
        ports: 
        - "5000:5000"
      register: container_info
    
    - name: print the container info
      ansible.builtin.debug:
        var: container_info